### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by anonymous1184** [tmorin/ff-cpdn#9]
Fantastic extension, for me is a must have!

However I would really love an option to also clean history and cache (for the domain of current tab). I mean, by clicking the icon close all the tabs from the domain of the current tan and clear all the related information (history/cache). First, Is doable? is in the scope?

Thnx, stay safe!

**Comment by tmorin** [comment]
hi @anonymous1184,
Thanks for the feedback.
It is possible to clear the history of pages matching the primary domain of the current ab.
For instance, to clear all pages having an URL matching the hostname `*.example.com`.
The change is in progress.
Best regards

**Comment by tmorin** [comment]
hi @anonymous1184 ,
The version 1.6.2 brings the wishes.
Best regards
